### ISSUE TITLE
IS-04: Automate remaining workshop/interop checklist items for RTP Transport

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#27]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Discovery & Registration (IS-04) Checklist
Version 2.2 (17th July 2018)
#### Section 2: RTP Transport

- [x] **2.1** Automated interpretation and multicast group join based on a valid SDP file for an ST.2110-20 RTP multicast stream
- [x] **2.2** Automated interpretation and multicast group join based on a valid SDP file for an ST.2110-30 RTP multicast stream
- [x] **2.3** Automated interpretation and multicast group join based on a valid SDP file for an ST.2110-40 RTP multicast stream
- [x] **2.4** Automated interpretation and multicast group join based on a valid SDP file for an ST.2022-6 RTP multicast stream
- [x] **2.5** Automated production of a valid SDP file for an ST.2110-20 RTP multicast stream
- [x] **2.6** Automated production of a valid SDP file for an ST.2110-30 RTP multicast stream
- [x] **2.7** Automated production of a valid SDP file for an ST.2110-40 RTP multicast stream
- [ ] **2.8** Automated production of a valid SDP file for an ST.2022-6 RTP multicast stream

**Comment by garethsb** [comment]
For senders, I believe sdpoker-based IS-05-01 test_41 covers **2.5**, **2.6** and **2.7** since https://github.com/AMWA-TV/nmos-testing/pull/195. sdpoker still doesn't support ST 2022-6/-8 as of now, so **2.8** is not yet covered.

For receivers, the NMOS Testing Tool cannot check the multicast group join, but has since https://github.com/AMWA-TV/nmos-testing/pull/442 been able to PATCH `transport_file` and that support has been made more flexible since then, so I'm also marking **2.1**, **2.2**, **2.3** and **2.4** as done.

**Comment by peterbrightwell** [comment]
This issue has been labelled as an enhancement and captured on the internal roadmap which will determine when resources can be allocated to address it.
