### ISSUE TITLE
IS-04: Automate remaining workshop/interop checklist items for Connection Management

### ISSUE THREAD

**Issue by garethsb-sony** [AMWA-TV/nmos-testing#29]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Discovery & Registration (IS-04) Checklist
Version 2.2 (17th July 2018)
#### Section 4: Connection Management

NB: Each of the below items should be checked off against each API version implemented.

- [x] **4.1** Node advertises valid Sender and Receiver resources via its Node API
- [x] **4.2** PUTing to a Receiver target resource with a Sender resource payload is accepted and connects the Receiver to a stream
- [x] **4.3** Receiver resource (in Node API and registry) is correctly updated to match the subscribed Sender ID upon subscription
- [x] **4.4** PUTing to a Receiver target resource with an empty JSON object payload is accepted and disconnects the Receiver from a stream
