### ISSUE TITLE
IS-04: Automate remaining workshop/interop checklist items for Clients

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#31]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Discovery & Registration (IS-04) Checklist
Version 2.2 (17th July 2018)
#### Section 6: Registry (and Connection Management) Clients

NB: Each of the below items should be checked off against each API version implemented.

- [ ] **6.1** Interface discovers a Query API via mDNS
- [ ] **6.2** Interface discovers a Query API via unicast DNS
- [ ] **6.3** Interface discovers required resources (Nodes, Devices etc) via the Query API
- [ ] **6.4** Interface updates based on dynamic changes from a Query API websocket
- [ ] **6.5** Connection manager instructs Receivers to subscribe to Senders via the Node API
- [ ] **6.6** Connection manager indicates success or failure of routing via updates received from the Query API
