### ISSUE TITLE
IS-05: Automate remaining workshop/interop checklist items for API Clients

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-testing#37]
Based on the most recent interop checklists, the following items remain to be automated if possible.
NB: Not all test cases are applicable for all Device Classes.

### AMWA NMOS Connection Management (IS-05) Checklist
Version 1.2 (2nd July 2018)

#### Section 6: API Clients

These checks only apply to API clients

- [x] **6.1** UI can discover Query API automatically
- [x] **6.2** UI can display Senders and Receivers from Query API
- [x] **6.3** UI updates via websocket when Senders and Receivers change
- [x] **6.4** UI can discover Devices with Connection Management APIs via the Query API data
- [ ] **6.5** UI can retune an RTP receiver using an SDP file
- [ ] **6.6** UI can configure an RTP transmitter for unicast sending
- [ ] **6.7** UI can configure an RTP receiver for unicast receiving
- [ ] **6.8** UI can enable/disable and configure 2022-7 on an RTP transmitter/receiver
- [ ] **6.9** UI can enable/disable and configure FEC on an RTP transmitter/receiver
- [ ] **6.10** UI can interact with both the deprecated Node API connection management, and the IS-05 Connection Management API

**Comment by garethsb-sony** [comment]
Automating these checks as black-box tests is obviously impossible, but perhaps a guided workflow is possible with appropriate mock Node, Connection and Query APIs?

**Comment by garethsb** [comment]
@jonathan-r-thorpe Did any of these get covered by the IS-05-03 "IS-05 Controller" test suite?

**Comment by peterbrightwell** [comment]
This issue has been labelled as an enhancement and captured on the internal roadmap which will determine when resources can be allocated to address it.
